server:
  port: 8081

spring:
  #  配置数据源
  datasource:
    username: root
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis
  redis:
    host:
    password: lty0712
    database: 0

  # RabbitMQ
  rabbitmq:
    host:
    port:
    username:
    password:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3        #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）

  # 文件上传大小限制
  servlet:
    multipart:
      enabled: true               #是否启用http上传处理
      max-request-size: 10MB     #最大请求文件的大小
      max-file-size: 8MB         #设置单个文件最大长度
      file-size-threshold: 10MB   #当文件达到多少时进行磁盘写入

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: github.qiao712.bbs.domain.entity
  configuration:
    map-underscore-to-camel-case: true

# 论坛系统设置
sys:
  token-valid-time: 3600
  remember-me-token-valid-time: 604800   #7天
  default-role-id: 1
  max-avatar-size: 1024000               #1000KiB
  max-post-image-size: 2097152           #2MiB
  max-post-image-num: 20
  max-comment-image-num: 10
  max-logo-image-size: 2097152           #2MiB
  min-temp-file-life: 86400              #1天
  max-advertisement-image-size: 2097152  #2MiB

  # 阿里云OOS配置
  aliOSS:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucket-name:

  # ElasticSearch地址
  elastic-search:
    hosts:
      - localhost:9200
    username: elastic
    password:
