server:
  port: 8081

spring:
  #  配置数据源
  datasource:
    username: root
    password: 5451876512
    url: jdbc:mysql://localhost:3306/my-bbs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis
  redis:
    host: localhost
    password: 5451876512
    database: 0

  # 文件上传大小限制
  servlet:
    multipart:
      enabled: true               #是否启用http上传处理
      max-request-size: 10MB     #最大请求文件的大小
      max-file-size: 8MB         #设置单个文件最大长度
      file-size-threshold: 10MB   #当文件达到多少时进行磁盘写入

  # Kafka
  kafka:
    bootstrap-servers: localhost:9092  #必须得写端口号
    # producer 生产者配置
    producer:
      retries: 3  # 重试次数
      acks: 1     # 应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      batch-size: 16384       # 批量大小
      buffer-memory: 33554432 # 生产端缓冲区大小
      # 序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # consumer 消费者配置
    consumer:
      group-id: default           # 默认的消费组ID
      enable-auto-commit: false    # 是否自动提交offset
      auto-commit-interval: 100   # 提交offset延时(接收到消息后多久提交offset)
      auto-offset-reset: earliest # earliest:当各分区下有已提交的offset时，从提交的offset开始消费；无提交的offset时，从头开始消费
      # 序列化器
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      type: single           # 批量消费
      ack-mode: manual       # 自动提交

  # 使用AntPathMatcher以兼容Swagger文档
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # 自动解决循环依赖
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: github.qiao712.bbs.domain.entity
  configuration:
    map-underscore-to-camel-case: true

# 论坛系统设置
sys:
  token-valid-time: 3600
  remember-me-token-valid-time: 604800   #7天
  default-role-id: 1
  max-avatar-size: 1024000               #1000KiB
  max-post-image-size: 2097152           #2MiB
  max-post-image-num: 20
  max-comment-image-num: 10
  max-logo-image-size: 2097152           #2MiB
  min-temp-file-life: 86400              #1天
  max-advertisement-image-size: 2097152  #2MiB

  # 阿里云OOS配置
  aliOSS:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tP3Jhgitq4fhuPWrEfS
    accessKeySecret: siBZmvrbPi165nudv7qSZ6ZNOBdibS
    bucket-name: qiao712-test-bucket

  # ElasticSearch地址
  elastic-search:
    hosts:
      - localhost:9200
    username: elastic
    password: 78787855
