server:
  port: 8081

spring:
  #  配置数据源
  datasource:
    username: root
    password: lty0712
    url: jdbc:mysql://localhost:3306/qa?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis
  redis:
    host: localhost
#    password:
    database: 0

  # 文件上传大小限制
  servlet:
    multipart:
      enabled: true               #是否启用http上传处理
      max-request-size: 10MB     #最大请求文件的大小
      max-file-size: 8MB         #设置单个文件最大长度
      file-size-threshold: 10MB   #当文件达到多少时进行磁盘写入

  # 使用AntPathMatcher以兼容Swagger文档
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # 自动解决循环依赖
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: sdu.addd.qasys.entity
  configuration:
    map-underscore-to-camel-case: true

# 论坛系统设置
sys:
  token-valid-time: 3600
  remember-me-token-valid-time: 604800   #7天
  default-role-id: 1
  max-post-image-num: 20
  max-comment-image-num: 10
  max-image-size: 102400000000
  max-tag-num: 10

  # 阿里云OOS配置
  aliOSS:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tH33YAeUdyNbcVp1tV3
    accessKeySecret: gs1XVoh88wSix8TDaYeCWEPTHK3Mlf
    bucket-name: addd-my-bbs

  # ElasticSearch地址
  elastic-search:
    hosts:
      - 114.116.245.83:9200
    username: elastic
    password: lty0712
